name: Build 
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    name: Build App
    runs-on: macOS-latest
    env:
      THEOS: theos
 
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: brew install ldid xz
      - name: Install Theos
        uses: Randomblock1/theos-action@v1.4
      - name: Download SDKs
        run: |
          curl -LO https://github.com/SamHep0803/iOS-13-Patched-SDK/archive/master.zip
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          mv $TMP/iOS-13-Patched-SDK-master/*.sdk theos/sdks
          rm -r master.zip $TMP
      - name: Build Package
        id: build_package
        run: |
          make package FINALPACKAGE=1
          echo "::set-output name=package::$(ls -t packages | head -n1)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_package.outputs.package }}
          
